<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BillOra.Domain\BillOra.Domain.csproj" />
    <ProjectReference Include="..\BillOra.Shared\BillOra.Shared.csproj" />
  </ItemGroup>
</Project>
